[dev]
  autoLaunch = false
  # command = "npm run build" # for for running algolia indexing locally
[context.dev.environment]
  SKIP_INDEXING = "false" # for running algolia indexing locally
[build]
  command = "GATSBY_EXPERIMENTAL_PAGE_BUILD_ON_DATA_CHANGES=true gatsby build --prefix-paths && mkdir blog && mv public/* blog && mv blog public/ && mv public/blog/_redirects public/_redirects"
  publish = "public"
[build.environment]
  NODE_VERSION = "12"
  MAILCHIMP_LIST_ID = "c59c3cf70b"
  WORDPRESS_URL = "https://wp.apollographql.com/graphql"
