[build]
  publish = "public"
  command = "GATSBY_EXPERIMENTAL_PAGE_BUILD_ON_DATA_CHANGES=true gatsby build --log-pages --prefix-paths && mkdir blog && mv public/* blog && mv blog public/"
  functions = "functions"
[[plugins]]
  package = "netlify-plugin-gatsby-cache"
[[redirects]]
  from = "/"
  to = "/blog"
